package gerudok.errorhandler;

public enum ExceptionEnum {
    WORKSPACE_RENAME, WORKSPACE_DELETE, NODE_RENAME_EMPTY, NODE_SAME_NAME, NO_SELECTED_DOCUMENT,
    NO_SELECTED_DELETE ,NO_SELECTED_TAB, NO_SELECTED_PAGE, LOAD_ERROR, CONTEXT_ERROR, WRONG_SELECTED_SAVE, MULTIPLE_SELECTION;
}
